name: ci-release

on:
    push:
        branches:
            - stage

jobs:
    job-release:
        name: CI Release
        if: github.repository_owner == 'ARQAWA'
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    persist-credentials: false

            -   name: Release
                uses: cycjimmy/semantic-release-action@v4
                id: semantic_release_step
                with:
                    semantic_version: 22.0.9
                    extra_plugins: |
                        @semantic-release/changelog@6.0.3
                        @semantic-release/git@10.0.1
                        conventional-changelog-conventionalcommits@7.0.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Update pyproject.toml
                run: |
                    NEW_VERSION=${{ steps.semantic_release_step.outputs.new_release_version }}
                    sed -i "s/^version = .*/version = \"$NEW_VERSION\"/" pyproject.toml

            -   name: Push changes
                run: |
                    git config --global user.name 'GitHub Action'
                    git config --global user.email 'action@github.com'
                    git add pyproject.toml
                    git commit --amend --no-edit || true
                    git push origin HEAD:${{ github.head_ref }} --force || true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
