name: ci-release

on:
  push:
    branches:
      - stage

jobs:
  job-release:
    name: CI Release
    if: github.repository_owner == 'ARQAWA'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22.0.9
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
