name: run-tests

on:
  push:
    branches-ignore:
      - main
      - stage

jobs:
  job-execute-tests:
    name: "Execute tests via docker-compose"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Docker Compose
        run: docker-compose up --exit-code-from web
